### ISSUE TITLE
Episeerr not following the keep rule

### ISSUE THREAD

**Issue by drmetro09** [Vansmak/episeerr#59]
I have this profile "get_count": 2,
"keep_type": "episodes",
"keep_count": 0,
"keep_pilot": true,
"monitor_watched": false
So as soon as episode is watched it should delete the previous episode but none of the episodes are getting deleted even on reaching the last episode of the season all episodes are still present i feel there is a bug.
But get is working fine that is if I watch the episode next episode are getting fetched so GET is working fine only the KEEP is not working

**Comment by drmetro09** [comment]
If i use polling mode , Also this error on playback stop error processing on
stop: name 'get_series_id' is not defined

**Comment by drmetro09** [comment]
![Image](https://github.com/user-attachments/assets/086652d4-e123-40ac-ac9b-20fcf1ab5aba)

**Comment by drmetro09** [comment]
Im very confused now the readme is also not helpful its old i guess.

**Comment by drmetro09** [comment]
The readme is not updated according to the latest changes the jellyfin webhook setup is still old insteuctions in the readme

**Comment by stayupthetree** [comment]
I am having the same issue. Can confirm its an Episeerr issue. It was deleting and searching for next episode, but now is just searching next episode and not removing anything. I don't use Jellyfin, I use Plex and Tautulli. Webhook setup in Tautulli is same as it was when it was working, I've changed absolutely nothing. I verified Tautulli can reach Episeerr with it's webhook. Verified Tautulli settings. Here is everything that happens when the webhook comes in



`2026-03-01 18:04:21,176 - INFO - ✓ Tag reconciliation complete: 0 moved, 3 synced, 0 orphaned
2026-03-01 18:04:21,176 - INFO - === Updating delay profile with control tags only ===
2026-03-01 18:04:21,180 - INFO - Using Episeerr delay profile ID 2
2026-03-01 18:04:21,182 - INFO - Found existing 'episeerr_default' tag with ID 14
2026-03-01 18:04:21,184 - INFO - Found existing 'episeerr_select' tag with ID 18
2026-03-01 18:04:21,188 - INFO - ✓ Updated delay profile with 3 control tags (default, select, delay)
2026-03-01 18:04:21,188 - INFO -   Control tag IDs: [14, 15, 18]
2026-03-01 18:04:21,188 - INFO - ✓ Delay profile updated with control tags (default, select, delay)
2026-03-01 18:04:21,190 - INFO - ✓ OCDarrScheduler instantiated successfully
2026-03-01 18:04:21,192 - INFO - ✅ Activity storage initialized with Sonarr config
2026-03-01 18:04:21,192 - INFO - ✅ Activity storage initialized with Sonarr config
2026-03-01 18:04:21,325 - INFO - Found TVDB ID match: Animal Control (TVDB: 423022)
2026-03-01 18:04:21,331 - INFO - Processing webhook for series 21: S4E6
2026-03-01 18:04:21,331 - INFO - 📺 Updated PER-SERIES activity for series 21: S4E6 at 2026-03-01 18:04:21
2026-03-01 18:04:21,332 - INFO - ✅ Config saved - series 21 activity data updated
2026-03-01 18:04:21,333 - INFO - 🔄 Watch detected - cleared grace_cleaned flag for series 21
2026-03-01 18:04:21,338 - INFO - 📝 Logged watch event: Animal Control S4E6 by System
2026-03-01 18:04:21,353 - INFO - Episodes [73850] successfully unmonitored.
2026-03-01 18:04:21,356 - INFO - Dropdown episodes mode: Found 7 out of 2 requested
2026-03-01 18:04:21,358 - INFO - Episodes [73851, 73852] successfully monitored.
2026-03-01 18:04:21,362 - INFO - Episode search command sent to Sonarr successfully.
2026-03-01 18:04:21,369 - INFO - 📝 Logged search event: Animal Control S4E7
2026-03-01 18:04:21,737 - INFO - 📤 Sent Discord message ID: 1477728215391801366
2026-03-01 18:04:21,738 - INFO - Sent episode_search_pending notification, message_id: 1477728215391801366
2026-03-01 18:04:21,739 - ERROR - Traceback: Traceback (most recent call last):
  File "/app/media_processor.py", line 723, in trigger_episode_search_in_sonarr
    store_pending_search(series_id, episode_ids, message_id)
    ^^^^^^^^^^^^^^^^^^^^
NameError: name 'store_pending_search' is not defined

2026-03-01 18:04:21,739 - INFO - Processed 2 next episodes
2026-03-01 18:04:21,739 - INFO - Keep block: episodes 36 to 36, 4 episodes leaving
2026-03-01 18:04:21,739 - ERROR - Error in webhook processing: cannot import name 'get_rule_for_series' from 'episeerr' (/app/episeerr.py)

2026-03-01 18:04:21,783 - INFO - Webhook processing completed - activity tracked, next content processed`

**Comment by drmetro09** [comment]
After updating to v3.3.9 im getting these errors in logs , its stil broken 

![Image](https://github.com/user-attachments/assets/18ccd007-e1f9-4656-b13a-f5f8ffba8495)
![Image](https://github.com/user-attachments/assets/6329a26c-b200-4acb-95c9-0b6d3821f490)

**Comment by drmetro09** [comment]
When webhook comes episeerr is crashing , this is happening since updated to v3.3.9 . Before this problem was not there and its happening constantly

**Comment by Vansmak** [comment]
You have to share logs or I'm just shooting in the dark

**Comment by stayupthetree** [comment]
> I am also using the Tautulli + Plex combination.
> 
> Have a look into your Tautulli logs, and check if those lines are repeating:
> 
> ```
> 2026-03-02 22:18:41 - ERROR :: ThreadPoolExecutor-2_1 : Failed to access uri endpoint /status/sessions. Connection error: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
> 2026-03-02 22:18:41 - WARNING :: ThreadPoolExecutor-2_1 : Tautulli Pmsconnect :: Unable to parse XML for get_current_activity: 'NoneType' object has no attribute 'getElementsByTagName'.
> 2026-03-02 22:18:41 - DEBUG :: ThreadPoolExecutor-2_1 : Tautulli Monitor :: Checking for active streams.
> 2026-03-02 22:18:41 - DEBUG :: ThreadPoolExecutor-2_1 : Tautulli Monitor :: Unable to read session list.
> 2026-03-02 22:18:41 - INFO :: Thread-2327 (run) : Tautulli WebSocket :: Opening websocket.
> 2026-03-02 22:18:41 - ERROR :: Thread-2327 (run) : Tautulli WebSocket :: Connection to remote host was lost..
> 2026-03-02 22:18:41 - INFO :: Thread-2327 (run) : Re-scheduled background task: Check for server response
> 2026-03-02 22:18:41 - DEBUG :: Thread-2327 (run) : Tautulli WebSocket :: Leaving thread.
> ```
> 
> I had them for the past several days. The issue was, that in Tautulli settings, the Plex server was not verified anymore and hence there was no connection from Plex to Tautulli. This might also be the reason for you. `Tautulli -> Settings -> Plex Media Server`, click on `Verify server` and check if it fails. If this is the case, click on `Fetch new Token` on the bottom. This solved it for me.

Me? That was definitely not the issue.
